AssetManagement/Models/AssetManagement/Facility.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AssetManagement.Models.AssetManagement
{
    public class Facility : BaseEntity
    {
        public Facility()
        {
            Resources = new List<Resource>();
        }
        [Key]
        public int FacilityId { get; set; }

        [Required]
        [Display (Name = "Facility Name")]
        public string FacilityName { get; set; }

        public string Landmark { get; set; }

        [Required]
        public string Address { get; set; }

        [Required]
        public string City { get; set; }

        [Required]
        public string State { get; set; }

        [MaxLength(5)]
        [Display (Name = "Zip Code")]
        public string ZipCode { get; set; }

        public List<Resource> Resources { get; set; }

        [Required]
        public Boolean IsActive { get; set; }

        public ApplicationUser User { get; set; }
        public String UserId { get; set; }
    }

    public class AssignFacility
    {
        public String Name { get; set; }

        public int FacilityId { get; set; }

        public Boolean Assign { get; set; }
    }
}

AssetManagement/Controllers/FacilitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AssetManagement.Data;
using AssetManagement.Models;
using AssetManagement.Models.AssetManagement;
using Microsoft.AspNet.Identity;

namespace AssetManagement.Controllers
{
    public class FacilitiesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        

        // GET: Facilities
        [Authorize(Roles = "Admin, Resource Checker")]
        public ActionResult Index()
        {
            var user = System.Web.HttpContext.Current.User.Identity.GetUserId();
            if (User.IsInRole("Admin"))
            {
                return View(db.Facilities.Where(f => f.IsActive == true).ToList());
            }
            else
            {
                return View(db.Facilities.Where(f => f.IsActive == true && f.UserId == user).ToList());
            }
            
        }

        public ActionResult ResourcesList(int id)
        {
            var relatedResources = db.Facilities.Include(r => r.Resources).SingleOrDefault(f => f.FacilityId == id);
            return View(relatedResources);
        }

        // GET: Facilities/Details/5
        [Authorize(Roles = "Admin, Resource Checker")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Facility facility = db.Facilities.Find(id);
            if (facility == null)
            {
                return HttpNotFound();
            }
            return View(facility);
        }

        // GET: Facilities/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Facilities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "FacilityId,FacilityName,Landmark,Address,City,State,ZipCode,UpdatedOn,IsActive")] Facility facility)
        {
            if (ModelState.IsValid)
            {
                facility.UpdatedOn = DateTime.Now;
                facility.IsActive = true;
                db.Facilities.Add(facility);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(facility);
        }

        // GET: Facilities/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Facility facility = db.Facilities.Find(id);
            if (facility == null)
            {
                return HttpNotFound();
            }
            return View(facility);
        }

        // POST: Facilities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "FacilityId,FacilityName,Landmark,Address,City,State,ZipCode,UpdatedOn,IsActive")] Facility facility)
        {
            if (ModelState.IsValid)
            {
                facility.UpdatedOn = DateTime.Now;
                facility.IsActive = true;
                db.Entry(facility).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(facility);
        }

        // GET: Facilities/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Facility facility = db.Facilities.Find(id);
            if (facility == null)
            {
                return HttpNotFound();
            }
            return View(facility);
        }

        // POST: Facilities/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Facility facility = db.Facilities.Find(id);
            List<Resource> resources = db.Resources.Where(r => r.FacilityId == id).ToList();
            foreach (var resource in resources)
            {
                resource.IsActive = false;
            }
            facility.IsActive = false;
            //db.Facilities.Remove(facility);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AssetManagement/Controllers/ResourceInventoryController.cs
using AssetManagement.Data;
using AssetManagement.Models.AssetManagement;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AssetManagement.Controllers
{
    public class ResourceInventoryController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Resources for the facility
        [Authorize(Roles = "Resource Checker")]
        public ActionResult Index(int id)
        {
            List<Resource> FacilityResources = db.Resources.Where(fr => fr.IsActive == true && fr.FacilityId == id).ToList();
            ResourceCheckList Inventory = new ResourceCheckList();
            Inventory.FacilityId = id;
            Inventory.ResourceList = new List<ResourceCheckViewModel>();
            foreach (var resource in FacilityResources)
            {
                ResourceCheckViewModel obj = new ResourceCheckViewModel()
                {
                    ResourceName = resource.ResourceName,
                    Color = resource.Color,
                    Description = resource.Description,
                    Size = resource.Size,
                    ResourceId = resource.ResourceId,
                    CurrentQuantity = resource.Quantity,
                    OriginalQuantity = resource.Quantity,
                    FacilityId = resource.FacilityId,
                    Comment = ""

                };
                Inventory.ResourceList.Add(obj);
            }
            return View(Inventory);
        }

        // POST: Save data to ResourceInventory table when Resource checker logs in and changes the quantities of resources
        [HttpPost]
        [Authorize(Roles = "Resource Checker")]
        public ActionResult Index(ResourceCheckList model)
        {
            foreach (var resource in model.ResourceList)
            {
                ResourceInventory record = new ResourceInventory
                {
                    ResourceId = resource.ResourceId,
                    CurrentQuantity = resource.CurrentQuantity,
                    Comment = resource.Comment,
                    UpdatedOn = DateTime.Now,
                    OriginalQuantity = resource.OriginalQuantity,
                    FacilityId = resource.FacilityId
                };
                db.ResourceInventories.Add(record);
                db.SaveChanges();
            }

            return RedirectToAction("Index", "Facilities", null);
        }
    }
}

AssetManagement/Views/Facilities/Create.cshtml
@model AssetManagement.Models.AssetManagement.Facility

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Facility</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FacilityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FacilityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FacilityName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Landmark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Landmark, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Landmark, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.UpdatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdatedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdatedOn, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AssetManagement/Views/Facilities/Delete.cshtml
@model AssetManagement.Models.AssetManagement.Facility

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Facility</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FacilityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Landmark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Landmark)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>*@

        @*<dd>
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AssetManagement/Views/Facilities/Details.cshtml
@model AssetManagement.Models.AssetManagement.Facility

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Facility</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FacilityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacilityName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Landmark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Landmark)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.FacilityId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AssetManagement/Views/Facilities/Edit.cshtml
@model AssetManagement.Models.AssetManagement.Facility

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Facility</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.FacilityId)

        <div class="form-group">
            @Html.LabelFor(model => model.FacilityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FacilityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FacilityName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Landmark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Landmark, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Landmark, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.UpdatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdatedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdatedOn, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AssetManagement/Views/Facilities/Index.cshtml
@model IEnumerable<AssetManagement.Models.AssetManagement.Facility>

@{
    ViewBag.Title = "Index";
}

<h2>Facilities</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FacilityName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Landmark)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ZipCode)
        </th>
        <th>
            Resources
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.UpdatedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <a href="/Facilities/ResourcesList/@item.FacilityId">@Html.DisplayFor(modelItem => item.FacilityName)</a>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Landmark)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ZipCode)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.UpdatedOn)
        </td>*@
        @*<td>
            @Html.DisplayFor(modelItem => item.IsActive)
        </td>*@
        @if (User.IsInRole("Admin"))
        {
         <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.FacilityId }) |
            @Html.ActionLink("Details", "Details", new { id=item.FacilityId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.FacilityId })
         </td>
        }
        @if(User.IsInRole("Resource Checker"))
        {
         <td>
             @Html.ActionLink("Perform Resource Check", "Index","ResourceInventory", new { id = item.FacilityId }, null)
         </td>
        }

    </tr>
}

</table>

AssetManagement/Views/Facilities/ResourcesList.cshtml
@model AssetManagement.Models.AssetManagement.Facility
@{
    ViewBag.Title = "Resources List";
}

<h2>Resources List</h2>

<table class="table">
    <tr>

        <th>
            <h5> Resource Name</h5>
        </th>
        <th>
            <h5> Quantity</h5>
        </th>
        <th>
            <h5> Colour</h5>
        </th>
        <th>
            <h5> Size</h5>
        </th>


        @*<th>
            @Html.DisplayNameFor(model => model.Landmark)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ZipCode)
        </th>*@
    </tr>    



    @foreach (var resoure in Model.Resources)
    {
        if (resoure.IsActive == true)
        {
    <tr>
        <td>
            @resoure.ResourceName
        </td>
        <td>
            @resoure.Quantity
        </td>
        <td>
            @resoure.Color
        </td>
        <td>
            @resoure.Size
        </td>
    </tr>

        }
    }
    </table>